#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Autostart
feh --bg-scale /etc/bgs/img1.jpg
ibus-daemon -drx &
xrandr --output eDP-1 --brightness $(cat ~/scripts/brightness)
polybar &
picom -f &
sleep 1s && dunst &
~/scripts/batwarn.sh &
flameshot &
#discord --start-minimized &
discord &
redshift &
xpad &

bspc monitor -d        漣  

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a xpad state=floating
